import { Button } from "std-widgets.slint";
import { ScoreTileExample } from "score_tiles.slint";

export component HelpWindow inherits Window {
    title: "使用说明";
    width: 800px;
    height: 600px;
    icon: @image-url("../svg/icon.svg");
    callback open-help-url();

    Text {
        x: 10px;
        y: 10px;
        font-size: 16px;
        width: 780px;
        height: 500px;
        wrap: word-wrap;
        text: "使用方式:\n打开程序后，程序会先从本地osu!目录读取6K游玩记录和谱面信息。加载完成后，通过左上角的下拉框选择玩家，或Recent 30即最近30次游玩记录。点击重置即可重新读取。";
    }

    Text {
        x: 10px;
        y: 80px;
        font-size: 16px;
        width: 780px;
        wrap: word-wrap;
        text: "之后程序会默认加载对应玩家最多30个最佳6K成绩。点击卡片左下角的灰色按钮可以将单个卡片复制到剪切板，之后可以在QQ等软件内直接粘贴发送。由于可能出现重复谱面或不想记录在B30列表中的谱面，可以点击卡片右下角红色减号按钮，将其移动到备选区，如果玩家游玩记录还有剩余就会在B30列表填充剩余的最好成绩。备选区的卡片右下角变成绿色加号按钮，点击即可替代B30列表最差的一个成绩。";
    }

    Text {
        x: 10px;
        y: 170px;
        font-size: 16px;
        width: 780px;
        wrap: word-wrap;
        text: "筛选完B30列表之后，点击导出按钮即可导出B30图片，导出完毕后程序界面会显示导出图片的路径。\n卡片信息如下：左侧是谱面背景，中间包括谱面的标题、音乐家、创作者、难度名等信息，中间下方是谱面的BPM、时长、难度和物件信息。右侧是游玩记录的排名、判定占比、Rating与定级、Rating Acc等。最下方是谱面的Hash（用于确认唯一性）和谱面ID。详情参见 https://github.com/Siflorite/mania-rating-gui";
    }

    Text {
        x: 10px;
        y: 260px;
        font-size: 16px;
        width: 780px;
        wrap: word-wrap;
        text: "0.2.0版本新增测试版实时模式。在程序启动后就会尝试读取osu!的内存，在完整游玩6K谱面之后就会生成最新的Rating卡片。由于使用的第三方库存在的一些问题，目前读取成绩确定游玩时间，且不能读取Replay使用的mod，因此必须经过完整的游玩过程。\n\n当前版本: v0.2.0";
    }

    Button {
        y: 350px;
        height: 40px;
        text: "访问详情页";
        clicked => {
           root.open-help-url();
        }
    }

    ScoreTileExample {
        x: 100px;
        y: 400px;
    }
}